### ISSUE TITLE
Questions about the license of this book

### ISSUE THREAD

**Issue by kozo2** [PlantsAndPython/PlantsAndPython#3]
Is it possible to translate into Japanese and redistribute this book?

**Comment by DanChitwood** [comment]
yes! it would be amazing if this were to be translated into Japanese! you are welcome to translate and redistribute into different languages. just be sure to credit and cite the original work (and let us know if you do, because we would love to see it and know about it if it happens!)

**Comment by kozo2** [comment]
Thanks for the permission.
I started translating this book into Japanese as follows.
https://github.com/kozo2/PlantsAndPython-Japanese/blob/dev/A_1_VARIABLES_LISTS_AND_INDEXING/1_Practice.ipynb

I will contact you again when the translation is complete.
I will close this issue for now.
